monthly_income = int(input("Enter your monthly income: "))
monthly_expenses = int(input("Enter your total monthly expenses: "))
monthly_Savings = (monthly_income - monthly_expenses)
Projected_Savings = (monthly_Savings * 12 + (monthly_Savings * 12 * 0.05))
print(f"Your monthly savings are {monthly_Savings} ")
print(f"Projected savings after one year, with interest, is: {Projected_Savings} ")