income = int(input("Enter your monthly income: "))
expenses = int(input("Enter your total monthly expenses: "))
Savings = (income - expenses)
Projected_Savings = (Savings * 12 + (Savings * 12 * 0.05))
print(f"Your monthly savings are {Savings} ")
print(f"Projected savings after one year, with interest, is: {Projected_Savings} ")